spring:
  application:
    name: dharma-education-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/dharma_education
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.dharma.education: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwtSecret: dharmaEducationSecretKeyForJWT2024
  jwtExpirationMs: 86400000 # 24 hours

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:dharma-education-media}
    region: ${AWS_REGION:us-east-1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/dharma_education_dev
  
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DATABASE_URL}
  
  jpa:
    show-sql: false
  
logging:
  level:
    com.dharma.education: INFO
    org.springframework.security: WARN