version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: dharma_education
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres

volumes:
  postgres_data: