// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olbmeapeusbvhkmippwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sYm1lYXBldXNidmhrbWlwcHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTEyMzcsImV4cCI6MjA3MDY4NzIzN30.HN0YBELj2BFWgP6w3pZHRMBsr42uiOR0hALptJuSKt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});